# Generated by Django 3.2 on 2022-05-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='part_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.orderline'),
            preserve_default=False,
        ),
    ]
